/** 构建期选择 API 实现；service 与 mapper 始终共用。 */
export { createOssClient, putOssPresignedUrl } from '@/domains/_shared/mock/ossClient.mock';
export { AdminUserApi } from '@/domains/Admin/mock/AdminUserApi.mock';
export { AgentApi } from '@/domains/Agent/mock/AgentApi.mock';
export { AuthApi } from '@/domains/Auth/mock/AuthApi.mock';
export { ChatApi, ChatCompletionApi, ChatSessionApi } from '@/domains/Chat/mock/ChatApi.mock';
export { DocumentApi } from '@/domains/Document/mock/DocumentApi.mock';
export { GroupApi, GroupMemberApi, GroupResConfigApi } from '@/domains/Group/mock/GroupApi.mock';
export { ImageApi } from '@/domains/Image/mock/ImageApi.mock';
export { InlineCommentApi } from '@/domains/InlineComment/mock/InlineCommentApi.mock';
export { CommentApi } from '@/domains/Interact/mock/CommentApi.mock';
export { FavoriteApi } from '@/domains/Interact/mock/FavoriteApi.mock';
export { InteractApi } from '@/domains/Interact/mock/InteractApi.mock';
export { MessageApi } from '@/domains/Message/mock/MessageApi.mock';
export { NoteApi } from '@/domains/Note/mock/NoteApi.mock';
export { ResourceItemApi } from '@/domains/Resource/mock/ResourceApi.mock';
export { ResourcePlacementApi } from '@/domains/Resource/mock/ResourcePlacementApi.mock';
export { SkillApi } from '@/domains/Skill/mock/SkillApi.mock';
export { SpeechApi } from '@/domains/Speech/mock/SpeechApi.mock';
export { TagApi } from '@/domains/Tag/mock/TagApi.mock';
export { UserApi, UserWalletApi } from '@/domains/User/mock/UserApi.mock';
